name: ParamaniacEnchants
main: io.github.minieyez.paramaniacenchants.ParamaniacEnchants
version: 1.1
description: Custom enchants made for Paramaniac Network!
author: MiDSama
depend: [WorldGuard, WorldEdit, Vault]
commands:
    paramaniacenchants: